export enum Frequence {
  PONCTUELLE = "PONCTUELLE",
  HEBDOMADAIRE = "HEBDOMADAIRE",
  MENSUELLE = "MENSUELLE",
  BIMESTRIELLE = "BIMESTRIELLE",
  TRIMESTRIELLE = "TRIMESTRIELLE",
  SEMESTRIELLE = "SEMESTRIELLE",
  ANNUELLE = "ANNUELLE"
}
